
spring:
  h2:
    console:
      enabled:  true


  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  security:
    user:
      name: sa
  jackson:
    serialization:
      indent_output: true


#server:
#  error:
#    whitelabel:
#      enabled: false
#    path: /error